version: "3"

volumes:
  flux_data:
  api_data:

networks:
  default:
    external: false

services:
  influx:
    image: influxdb:alpine
    ports:
      - 2003:2003
      - 8083:8083
      - 8086:8086
    volumes:
      - flux_data:/var/lib/influxdb
    environment:
      INFLUXDB_ADMIN_ENABLED: "true"

  api:
    image: thingy-api-red
    build: ./
    ports:
      - 8000:8000
    environment:
      NODE_PORT: 8000
      NODE_ENV: "development"
