version: "3"

networks:
  default:
    external: false

volumes:
  influx_data:
  postgres_data:
  api_data:

services:
  influx:
    image: influxdb:1.7-alpine
    ports:
      - "${FLUXDB_PORT}:8086"
    volumes:
      - influx_data:/var/lib/influxdb
      - ./resources/init-fluxdb:/docker-entrypoint-initdb.d
      - /etc/localtime:/etc/localtime:ro
    environment:
      INFLUXDB_ADMIN_USER: ${INFLUXDB_ADMIN_USER}
      INFLUXDB_ADMIN_PASSWORD: ${INFLUXDB_ADMIN_PASSWORD}
      INFLUXDB_HTTP_AUTH_ENABLED: "false"

  postgres:
    image: postgres:11-alpine
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./resources/init-postgres:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: ${POSTGRES_DBNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} 

  api:
    image: thingy-api-red
    build: ./
    restart: on-failure
    ports:
      - ${NODE_PORT}:8000
    volumes:
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - influx
      - postgres
    environment:
      NODE_PORT: ${NODE_PORT}
      NODE_ENV: ${NODE_ENV}
      FLUXDB_HOST: influx
      FLUXDB_PORT: ${FLUXDB_PORT}
      POSTGRES_HOST: postgres
      POSTGRES_PORT: ${POSTGRES_PORT}
      MQTT_HOST: ${MQTT_HOST}
      MQTT_PORT: ${MQTT_PORT}
      MQTT_USER: ${MQTT_USER}
      MQTT_PW: ${MQTT_PW} 
