name: "Deploy thingy-api-red"
on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Prepare env variables
        run: cp .env.example .env && echo MQTT_USER=$MQTT_USER >> .env && echo MQTT_PW=$MQTT_PW >> .env
        env:
          MQTT_USER: ${{ secrets.MQTT_USER }}
          MQTT_PW: ${{ secrets.MQTT_PW }}

      - name: Prepare keys
        run: echo $VPS_KEY > ~/.ssh/id_rsa && echo $VPS_PUB_KEY > ~/.ssh/id_rsa.pub
        env:
          VPS_KEY: ${{ secrets.VPS_KEY }}
          VPS_PUB_KEY: ${{ secrets.VPS_PUB_KEY }}

      - name: Deploy app with docker stack deploy using the production compose file
        run: export DOCKER_HOST=ssh://$DEPLOY_USER@$SERVER_IP && docker stack deploy --compose-file docker-compose-production.yaml thingy-api-red
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
