name: "Deploy thingy-api-red"
on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Prepare env variables
        run: cp .env.example .env && echo MQTT_USER=$MQTT_USER >> .env && echo MQTT_PW=$MQTT_PW >> .env
        env:
          MQTT_USER: ${{ secrets.MQTT_USER }}
          MQTT_PW: ${{ secrets.MQTT_PW }}

      - name: Prepare keys
        run: echo $DOCKER_CA > ca.pem && echo $DOCKER_CERT && echo $DOCKER_KEY > key.pem
        env:
          DOCKER_CA: ${{ secrets.DOCKER_CA }}
          DOCKER_CERT: ${{ secrets.DOCKER_CERT }}
          DOCKER_KEY: ${{ secrets.DOCKER_KEY }}

      - name: Deploy app with docker stack deploy using the production compose file
        run: docker stack deploy --compose-file docker-compose-production.yaml thingy-api-red
        env:
          DOCKER_TLS_VERIFY: 1
          DOCKER_HOST: tcp://51.15.233.22:2376
          DOCKER_CERT_PATH=: $PWD